# Detección de outliers
Buscamos aquellos valores que se salen de los percentiles, y los reemplazamos por una interpolación, columna por columna.

In [16]:
import pandas as pd
import numpy as np

df = pd.read_excel("../data/LatLon20210801.xlsx", sheet_name="Sheet1")
df.fillna(0, inplace=True)
print("df ANTES de la interpolación:")
print(df.head(30))

whisker_width = 1.5
for column in ['Lat','Lon']:
    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)
    iqr = q3 - q1
    lower_whisker = q1 - whisker_width*iqr
    upper_whisker = q3 + whisker_width*iqr
    df[column] = np.where(df[column] > upper_whisker, np.nan, df[column])
    df[column] = np.where(df[column] < lower_whisker, np.nan, df[column])
    df[column] = df[column].interpolate().ffill().bfill()
    print("df DESPUÉS de la interpolación de la columna " + column)
    print(df.head(30))

df ANTES de la interpolación:
              DateTime  Lat        Lon
0  2021-08-01 00:00:00  0.0   0.000000
1  2021-08-01 00:01:00  0.2   5.226423
2  2021-08-01 00:02:00  0.4  10.395585
3  2021-08-01 00:03:00  0.6  15.450850
4  2021-08-01 00:04:00  0.8  20.336832
5  2021-08-01 00:05:00  1.0  25.000000
6  2021-08-01 00:06:00  1.2  29.389263
7  2021-08-01 00:07:00  1.4  33.456530
8  2021-08-01 00:08:00  1.6  37.157241
9  2021-08-01 00:09:00  1.8  40.450850
10 2021-08-01 00:10:00  0.0   0.000000
11 2021-08-01 00:11:00  2.2  45.677273
12 2021-08-01 00:12:00  2.4  47.552826
13 2021-08-01 00:13:00  2.6  48.907380
14 2021-08-01 00:14:00  2.8  49.726095
15 2021-08-01 00:15:00  3.0  50.000000
16 2021-08-01 00:16:00  3.2  49.726095
17 2021-08-01 00:17:00  3.4  48.907380
18 2021-08-01 00:18:00  3.6  47.552826
19 2021-08-01 00:19:00  3.8  45.677273
20 2021-08-01 00:20:00  0.0   0.000000
21 2021-08-01 00:21:00  4.2  40.450850
22 2021-08-01 00:22:00  4.4  37.157241
23 2021-08-01 00:23:00  4.6  33.456530
24 2021-08-01 00:24:00  4.8  29.389263
25 2021-08-01 00:25:00  5.0  25.000000
26 2021-08-01 00:26:00  5.2  20.336832
27 2021-08-01 00:27:00  5.4  15.450850
28 2021-08-01 00:28:00  5.6  10.395585
29 2021-08-01 00:29:00  5.8   5.226423
df DESPUÉS de la interpolación de la columna Lat
              DateTime  Lat        Lon
0  2021-08-01 00:00:00  0.0   0.000000
1  2021-08-01 00:01:00  0.2   5.226423
2  2021-08-01 00:02:00  0.4  10.395585
3  2021-08-01 00:03:00  0.6  15.450850
4  2021-08-01 00:04:00  0.8  20.336832
5  2021-08-01 00:05:00  1.0  25.000000
6  2021-08-01 00:06:00  1.2  29.389263
7  2021-08-01 00:07:00  1.4  33.456530
8  2021-08-01 00:08:00  1.6  37.157241
9  2021-08-01 00:09:00  1.8  40.450850
10 2021-08-01 00:10:00  0.0   0.000000
11 2021-08-01 00:11:00  2.2  45.677273
12 2021-08-01 00:12:00  2.4  47.552826
13 2021-08-01 00:13:00  2.6  48.907380
14 2021-08-01 00:14:00  2.8  49.726095
15 2021-08-01 00:15:00  3.0  50.000000
16 2021-08-01 00:16:00  3.2  49.726095
17 2021-08-01 00:17:00  3.4  48.907380
18 2021-08-01 00:18:00  3.6  47.552826
19 2021-08-01 00:19:00  3.8  45.677273
20 2021-08-01 00:20:00  0.0   0.000000
21 2021-08-01 00:21:00  4.2  40.450850
22 2021-08-01 00:22:00  4.4  37.157241
23 2021-08-01 00:23:00  4.6  33.456530
24 2021-08-01 00:24:00  4.8  29.389263
25 2021-08-01 00:25:00  5.0  25.000000
26 2021-08-01 00:26:00  5.2  20.336832
27 2021-08-01 00:27:00  5.4  15.450850
28 2021-08-01 00:28:00  5.6  10.395585
29 2021-08-01 00:29:00  5.8   5.226423
df DESPUÉS de la interpolación de la columna Lon
              DateTime  Lat        Lon
0  2021-08-01 00:00:00  0.0   0.000000
1  2021-08-01 00:01:00  0.2   5.226423
2  2021-08-01 00:02:00  0.4  10.395585
3  2021-08-01 00:03:00  0.6  15.450850
4  2021-08-01 00:04:00  0.8  20.336832
5  2021-08-01 00:05:00  1.0  25.000000
6  2021-08-01 00:06:00  1.2  29.389263
7  2021-08-01 00:07:00  1.4  33.456530
8  2021-08-01 00:08:00  1.6  37.157241
9  2021-08-01 00:09:00  1.8  40.450850
10 2021-08-01 00:10:00  0.0   0.000000
11 2021-08-01 00:11:00  2.2  45.677273
12 2021-08-01 00:12:00  2.4  47.552826
13 2021-08-01 00:13:00  2.6  48.907380
14 2021-08-01 00:14:00  2.8  49.726095
15 2021-08-01 00:15:00  3.0  50.000000
16 2021-08-01 00:16:00  3.2  49.726095
17 2021-08-01 00:17:00  3.4  48.907380
18 2021-08-01 00:18:00  3.6  47.552826
19 2021-08-01 00:19:00  3.8  45.677273
20 2021-08-01 00:20:00  0.0   0.000000
21 2021-08-01 00:21:00  4.2  40.450850
22 2021-08-01 00:22:00  4.4  37.157241
23 2021-08-01 00:23:00  4.6  33.456530
24 2021-08-01 00:24:00  4.8  29.389263
25 2021-08-01 00:25:00  5.0  25.000000
26 2021-08-01 00:26:00  5.2  20.336832
27 2021-08-01 00:27:00  5.4  15.450850
28 2021-08-01 00:28:00  5.6  10.395585
29 2021-08-01 00:29:00  5.8   5.226423

In [1]:
for i in range(1, 4):
    print(i)

1
2
3

In [2]:
for dtype in ["raw", "mod"]:
    print(dtype)

raw
mod